services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: anba_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    env_file:
      - .env
      - .env.local
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:latest
    container_name: anba_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: anba_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anba
      MYSQL_USER: anba_user
      MYSQL_PASSWORD: anba_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf

  redis:
    image: redis:latest
    container_name: anba_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  mysql_data:
